BulkUpload Response broken
I don't think this has always been a problem, but when I tested recently it was.
When I upload an image with the BulkUploader, it uploads just fine, but the ajax response is corrupted and the download bar turns red.

Investigating further I get
```
Fatal error: Call to a member function Link() on a non-object in C:\wamp\www\snwp_v31\GridFieldBulkEditingTools\code\GridFieldBulkImageUpload_Request.php on line 375

which is:
'preview_url' => $uploadedFile->setHeight(55)->Link(),
```

I noticed that if I move ```$uploadedFile->setHeight(55)->Link()``` to line 362 as the pull request shows, it seems to work just fine.
I have no idea why it is behaving this way, but this seems to have fixed it for me